version: '3.3'
services:
  redcap-web:
    build:
      context: ./Webservice
      #args:
         #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         #MYSQL_DATABASE: ${MYSQL_DATABASE}
         #MYSQL_USER: ${MYSQL_USER}
         #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         #APACHE_DOCUMENT_ROOT: /var/www/html/redcap
    environment:
         APACHE_DOCUMENT_ROOT: /var/www/html/redcap
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #  XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
      #  XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
      #  XNAT_DATASOURCE_USERNAME: 'xnat'
      #  XNAT_DATASOURCE_PASSWORD: 'xnat'
      #  XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
      #  TOMCAT_XNAT_FOLDER: ROOT
      #  XNAT_ROOT: /data/xnat
      #  XNAT_HOME: /data/xnat/home
    ports:
      - "80:80"
    #volumes:
      #- /Xnat-Ubuntu/sharedData:/data/xnat/sharedData
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /data/xnat/archive:/data/xnat/archive
      #- /data/xnat/build:/data/xnat/build
    #environment:
      #- CATALINA_OPTS=-Xms128m -Xmx1024m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      #- XNAT_HOME=/data/xnat/home
    expose:
      - "80"
  redcap-db:
    build: ./MariaDB
    expose:
      - "3306"
    environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - /data/example/mysql:/var/lib/mysql
    restart: always
    links:
      - redcap-web:redcap-db

  #redcap-nginx:
  #  build: ./Nginx
  #  ports:
  #    - "80:80"
  #  expose:
  #    - "80"
  #  depends_on:
  #    - redcap-web
  #  links:
  #    - redcap-web
