version: '3.3'
services:

# compose section for the redcap webservice
  redcap-web:
    env_file: ./.env
    build:
      context: ./Webservice
    environment:
         APACHE_DOCUMENT_ROOT: /var/www/html/redcap
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         REDCAP_VERSION: ${REDCAP_VERSION}
         REDCAP_BASE_URL: ${REDCAP_BASE_URL}
         INSTITUTION: ${INSTITUTION}
         DEPARTMENT: ${DEPARTMENT}
         CONTACT_EMAIL: ${CONTACT_EMAIL}
         ADMINISTRATOR_NAME: ${ADMINISTRATOR_NAME}
    depends_on:
      - redcap-db
# open https ports
    ports:
      - "80:80"
      - "443:443"
# merge key and certificate folders (local <-> container)
    volumes:
      - ./Webservice/ssl/crt:/etc/ssl/certs
      - ./Webservice/ssl/key:/etc/ssl/private
    expose:
      - "80"
    container_name: redcap-web

# compose section for the database
  redcap-db:
    build:
      context: ./MariaDB
    expose:
      - "3306"
# set your specified values
    environment:
         MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MARIADB_DATABASE: ${MYSQL_DATABASE}
         MARIADB_USER: ${MYSQL_USER}
         MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    container_name: redcap-db
