FROM php:7.4-apache
MAINTAINER Adrian Pfleiderer <github@adrian-pfleiderer.de>

RUN			apt-get update && \
				apt-get install -y curl && \
				apt-get install -y unzip && \
				apt-get install nano && \
				docker-php-ext-install mysqli

COPY src/ /var/www/html
RUN	unzip /var/www/html/*.zip

ENV APACHE_DOCUMENT_ROOT /var/www/html/redcap
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN 		sed -i "s|your_mysql_host_name|localhost:3306|g" /var/www/html/redcap/database.php && \
 				sed -i "s|your_mysql_db_name|$MYSQL_DATABASE|g" /var/www/html/redcap/database.php && \
 				sed -i "s|your_mysql_db_username|$MYSQL_USER|g" /var/www/html/redcap/database.php && \
				sed -i "s|your_mysql_db_password|$MYSQL_PASSWORD|g" /var/www/html/redcap/database.php

CMD apachectl -D FOREGROUND
